version: '2'
services:
  node-app:
    image: node:10
    links:
      - redis-db
    user: node
    container_name: node-app
    working_dir: /home/node/app
    volumes:
      - ./node-app:/home/node/app
    environment:
      - NODE_ENV=development
      - PORT=3040
      - REDIS_HOST=redis-db
    command: node app.js
    # ports:
    #   - "3333:3040"
  nginx:
    image: nginx
    container_name: nginx-app
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html/index.html:/usr/share/nginx/html/index.html:ro
    links:
      - node-app
    ports:
      - "8080:80"
  redis-db:
    image: redis
    container_name: redis-db
