version: '0.1.0'
services:
  #node-app:
  #  container_name: node-app
  #  depends_on:
  #    - node-app
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html

    #depends_on:
    #  - node-app
    ports:
      - "8080:80"
