version: '0.1.3'
services:
  node-app:
    image: 'node:10'
    user: node
    container_name: node-app
    working_dir: /home/node/app
    volumes:
      - ./node-demo-app:/home/node/app
    environment:
      - NODE_ENV=development
      - PORT=3040
    command: node app.js
    # ports:
    #   - "3333:3040"
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    links:
      - node-app
    ports:
      - "8080:80"
